blank_issues_enabled: false
contact_links:
    - name: Q & A
      url: https://github.com/eamodio/vscode-restore-editors/discussions?discussions_q=category%3AQ%26A
      about: Ask and answer questions about Restore Editors
    - name: Documentation
      url: https://github.com/eamodio/vscode-restore-editors/#readme
      about: Read the Restore Editors support documentation
